[workspace]
members = [ "crates/*" ]
resolver = "3"
package.edition = "2024"

[workspace.dependencies]
mars_math = { path = "crates/mars_math" }
mars_surface = { path = "crates/mars_surface" }
mars_terminal = { path = "crates/mars_terminal" }
