[package]
name = "mars_terminal"
version = "0.1.0"
edition.workspace = true

[dependencies]
mars_math.workspace = true

termina = { git = "https://github.com/helix-editor/termina", rev = "b7f6c327a64533c5c798e2c409191620b75c492e" }
